/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudySession = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'days' : IDL.Nat,
  'difficulty' : IDL.Text,
  'quiz' : IDL.Text,
  'concepts' : IDL.Text,
  'studyPlan' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'deleteSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateStudyContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(StudySession)], ['query']),
  'getSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudySession = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'days' : IDL.Nat,
    'difficulty' : IDL.Text,
    'quiz' : IDL.Text,
    'concepts' : IDL.Text,
    'studyPlan' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'deleteSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateStudyContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(StudySession)], ['query']),
    'getSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };